/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */
/* SUPABASE DISCONNECTED */

export const set = async (key: string, value: any): Promise<void> => {
  throw new Error("Supabase disconnected");
};

export const get = async (key: string): Promise<any> => {
  return null;
};

export const del = async (key: string): Promise<void> => {
  throw new Error("Supabase disconnected");
};

export const mset = async (keys: string[], values: any[]): Promise<void> => {
  throw new Error("Supabase disconnected");
};

export const mget = async (keys: string[]): Promise<any[]> => {
  return [];
};

export const mdel = async (keys: string[]): Promise<void> => {
  throw new Error("Supabase disconnected");
};

export const getByPrefix = async (prefix: string): Promise<any[]> => {
  return [];
};
